### ISSUE TITLE
Authentication may fails beause auth type doesn't work with default value

### ISSUE THREAD

**Issue by benoitchantre** [soup-bowl/wp-simple-smtp#121]
**What WordPress, PHP and Simple SMTP versions are you using?**
WordPress 5.8.3

**Describe the bug**
The default authentication type may not work for all SMTP providers, and in that case there's no way to change the Authtype property used by PHPMailer.

**Expected behavior**
There should be an additional setting / environment variable to change the default value.

Related issue: #117

**Comment by soup-bowl** [comment]
Will look into this since #59 will also require this,  but this should work automatically, as the PHPMailer [conmmand docs](https://github.com/PHPMailer/PHPMailer/blob/master/src/PHPMailer.php#L354) (well, the var doc, quick lookup) states:

> Options are CRAM-MD5, LOGIN, PLAIN, XOAUTH2, attempted in that order if not specified.

Might be worth considering reporting a bug to PHPMailer if it isn't working on your server?

**Comment by benoitchantre** [comment]
> Might be worth considering reporting a bug to PHPMailer if it isn't working on your server?

Unfortunately, I don’t have any access to the staging and production servers and the SMTP service is restricted to their IP. I don’t think it will be useful to open a ticket when I don’t have access to reproduce the issue again.
