### ISSUE TITLE
ClassicPress compatibility 

### ISSUE THREAD

**Issue by atomGit** [soup-bowl/wp-simple-smtp#133]
hi!

please consider making your plugin compatible with ClassicPress - a fork of WP 4.9 (soon to be a fork of v6)

given that your plugin is supposed to support WP 4.9, normally it would just work, but for some reason it doesn't - the http status for the settings page is 500: `options-general.php?page=wpsimplesmtp`

php v8

**Comment by soup-bowl** [comment]
Looks like the minimum version is incorrect - I've run a quick test on this on a ClassicPress Docker image, and it looks the error is from the lack of [wp_set_script_translations](https://developer.wordpress.org/reference/functions/wp_set_script_translations/), which was introduced in v5. It must've been missed when translation support was added.

Thanks for pointing this out - I'll increase the minimum version spec. I can't speak for ClassicPress compatibility, but if they introduce i18n support from newer WordPress versions, then this should work out the box.

**Comment by atomGit** [comment]
if i wanted to run the plugin in classicpress (wp 4.9) temporarily until CP v6 is released, could you tell me what i would need to modify (besides min. version)?

if it's a simple matter of editing/commenting a line of code, that would be great - if it's a matter of a larger change, please don't waste your time on it just for lil' ol' me

**Comment by soup-bowl** [comment]
Oh sorry, comment out line 96 of wp-simple-smtp.php:

`wp_set_script_translations( 'wpss_config', 'simple-smtp' );`

This will stop the 500 error, in exchange for the 'quick configurations' widget not adjusting for non-English locales. To clarify, I've only tested quickly (I set mail settings, SMTP log and sent an email) so since it's a different platform there might be other bugs, but I was able to send an email successfully :)

**Comment by atomGit** [comment]
thanks much!

i have a ? i wanted to ask re: password storage - didn't want to open a new issue for this

you recommend storing the password in wp-config vs. storing it encrypted in the db

may i ask why, because i would think storing it in the db -- as long as it's encrypted (not hashed or plain text) -- would be even more secure than storing a plain text pwd in the config file

**Comment by soup-bowl** [comment]
No problem - I was unaware of ClassicPress, so if you don't mind I'll keep this issue open until v6 is out, and if they keep a feature parity with WordPress (obviously ignoring Gutenberg/Block Editor), i'll consider officially adding CP support.

> you recommend storing the password in wp-config vs. storing it encrypted in the db

The disclaimer has been in place from before the password encryption was implemented, and is kept in generally in case of some setup scenarios w/o OpenSSL can cause passwords to be saved plaintext. Storing them in the wp-config file is therefore safer since - while still being plaintext - the wp-config file should be [locked down to prevent user access](https://stackoverflow.com/a/57762048) (esp. since other access keys are often stored here). I'd like to say that servers w/o OpenSSL are non-existent nowadays, but unfortunately have come across it before.

Generally speaking both should be fine. But on awareness that users would be likely to opt for the convinience of storing passwords in the DB (and especially in MS installs with multiple email servers), I added the password encryption to provide some safeguarding against an attack with query access from dumping the SMTP password.

**Comment by atomGit** [comment]
all is well - the plugin works with ClassicPress 1.5/WordPress 4.9 with the edit you kindly provided

deleting individual mails doesn't work, but purging all mails does - no problem for me whatsoever

i decided to store the pw in the db - is there a way i can make sure it's encrypted? i looked in the options table and i'm seeing...

`"pass";s:44:"<string>=";s:4:`

...where `<string>` is definitely not my pw - it's also about twice as many chars - that, and the '=' char at the end, has me suspecting it's encrypted and not just hashed

**Comment by soup-bowl** [comment]
Aye, there'll also be a `pass_d` that'll be set to 1 to assist the code that handles decoding the password for dispatch. The key/salt is derived from the `SECURE_AUTH_KEY` in wp-config.php and encryption uses AES-128-ECB.

Basically yes, if the password is different in the DB to the one you input, then it's encrypted. IIRC, there's a warning dialog that's displayed in the event there's no OpenSSL installed too.
