### ISSUE TITLE
`LogService::prune_logs` removes old posts from custom post type

### ISSUE THREAD

**Issue by soup-bowl** [soup-bowl/wp-simple-smtp#168]
From the plugin forums posted by @odkr:

https://wordpress.org/support/topic/logservice-prune_logs-removes-old-posts-from-custom-post-type/

There is a proven concern that the post cleanup scheduler has the possibility to delete posts that aren't from the CPT of the plugin.

**Comment by odkr** [comment]
I had some time to think about this since I opened the issue, and it would seem to me that it comes down to is that the expectation that a `WP_Query` returns the posts that the query was for, while reasonable, may not hold up in the real world, for three reasons:

1. `is_home()`, `is_blog()` have counter-intuitive edge cases; in my case, that `is_home()` holds true for any query made using `get_posts`, even if it is made in a cron job. Moreover, plugins may run arbitrary queries and modify them in arbitrary ways that are not covered by conditional tags to begin with (e.g., plugins for plugins).

2. The WP Codex offers little normative guidance what to use `pre_get_posts`, `parse_query`, `query`, etc. for and how to use them, so any query may be modified. In fairness, it *does* say that functions that hook into `pre_get_posts` should use `is_main_query()`. I forgot about that because it's counter-intuitive to me that `is_home() == true` does not imply `is_main_query() == true` or that `get_posts` would ever hold true in a cron job.

3. There are people, like me 😄 , whose intuitions do not fit WordPress' API.

So I'd still recommend to check the post type before calling `wp_delete_post()`. Deleting posts may have far-ranging consequences (in our case, the cron job deleted roughly 2,000 posts that pre-dated the installation of WP Simple SMTP; some people don't make backups, or so I've been told). What is more, because it only deletes old posts, the deletion may go unnoticed for a while (we make backups; but it took us some days so to notice, so we couldn't just revert to the backup from two hours ago, but had to merge backups with the content added since then).
