### ISSUE TITLE
Log Settings Discussion

### ISSUE THREAD

**Issue by soup-bowl** [soup-bowl/wp-simple-smtp#77]
Since logging was added, there's now been a few additional requests for functionality tailoring.
- Issue #57 for allowing users to change the log pagination.
- Issues #70 and #71 about purging logs.

It may now be a good time to add configurable options to the log viewer, to let people set their configuration choices via the GUI. A first-pass mock-up could look like this:
![image](https://user-images.githubusercontent.com/11209477/148691471-36bf01bd-90b8-4bbc-8144-76561b4e2f33.png)
(Considering splitting the latter two under a seperate heading since the pagination count could be changed into a user variable instead of a system one).

Thoughts welcome.

**Comment by benoitchantre** [comment]
Here are my two cents: I think one the the strength of this plugin is to have a clean UI and to follow the WordPress philosophy: decision, not options. If some settings don't need a UI because the default value is good enough, I would prefer that.

For the numbers of items per page, a default value of 20 seems good. The current value of 5 is probably a bit low for users keeping the log feature enabled.

For the clean-up schedule, I would go with a default value of 15 days, eventually one month (no more) to prevent keeping too many logs containing personal data to be compliant with GDPR (privacy by default). To prevent a change for existing users, this could be enabled only during plugin activation.

From a privacy point of view, I see no interest to keep log data when the plugin is uninstalled. That should be done automatically to be compliant with GDPR (privacy by default).

**Comment by soup-bowl** [comment]
@benoitchantre fantastic thoughts, and I agree wholeheartedly. I'm not in favour of my own suggestion (more of a compromise), but your points actually cover the basis of this better.

>If some settings don't need a UI because the default value is good enough, I would prefer that.

This is generally a philosophy of this plugin, since my core concept is to make this plugin look like it was rolled into WordPress itself (no ads, no complexity, simple titles and names where possible, etc). This reminds me to add a policy document to explain these concepts if this plugin starts getting more attention.

In our use cases we do actually use the historical data, but I'd agree to setting this perhaps to a **default of a month**. The regular use case I see for this is just checking dispatch is working, but I can provide a filter over-ride for changing the schedule or disabling for those particular use cases. I also appreciate your added concern for existing installations.
